// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dYaItO2dTT59uMOv8mpsMfLTMPlHwa0',
    appId: '1:1029777607545:web:e03ae03996fa0c70203da8',
    messagingSenderId: '1029777607545',
    projectId: 'melomilkrashid',
    authDomain: 'melomilkrashid.firebaseapp.com',
    storageBucket: 'melomilkrashid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa5MCGMrsyjJWyqgzQW4n6PMrrgeAO224',
    appId: '1:1029777607545:android:527941d0033480e7203da8',
    messagingSenderId: '1029777607545',
    projectId: 'melomilkrashid',
    storageBucket: 'melomilkrashid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuVZHijG38nCHZYE3cazzAdZq7m3C3G94',
    appId: '1:1029777607545:ios:00fc298755bdc9da203da8',
    messagingSenderId: '1029777607545',
    projectId: 'melomilkrashid',
    storageBucket: 'melomilkrashid.appspot.com',
    iosClientId: '1029777607545-50sl200gg6tjl1qp5hlsghitquco9je2.apps.googleusercontent.com',
    iosBundleId: 'com.example.meloMilk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuVZHijG38nCHZYE3cazzAdZq7m3C3G94',
    appId: '1:1029777607545:ios:f734ea700b029d76203da8',
    messagingSenderId: '1029777607545',
    projectId: 'melomilkrashid',
    storageBucket: 'melomilkrashid.appspot.com',
    iosClientId: '1029777607545-ideeg1un6425a8roc043utnvmgkn3p2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.meloMilk.RunnerTests',
  );
}
